// Fetches skill reference files from the private Jayasom-wireframe-generator repo
// and writes them into src/lib/skill-content.ts as exported strings.
// Runs as `prebuild` so every Vercel build / local build has the latest skill bundled.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const REPO_OWNER = 'shemoelnexa';
const REPO_NAME = 'Jayasom-wireframe-generator';
const BRANCH = 'main';
const TOKEN = process.env.GITHUB_TOKEN;

const FILES = [
  'SKILL.md',
  'references/design-tokens.css',
  'references/component-library.html',
  'references/section-patterns.md',
  'references/content-inference.md',
  'references/output-template.html',
];

if (!TOKEN) {
  console.error('GITHUB_TOKEN env var is required');
  process.exit(1);
}

async function fetchFile(path) {
  const url = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${path}?ref=${BRANCH}`;
  const res = await fetch(url, {
    headers: {
      'Authorization': `Bearer ${TOKEN}`,
      'Accept': 'application/vnd.github.raw',
      'User-Agent': 'jayasom-wireframe-prebuild',
    },
  });
  if (!res.ok) {
    throw new Error(`Failed to fetch ${path}: ${res.status} ${await res.text()}`);
  }
  return await res.text();
}

function escapeForTemplate(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

async function main() {
  console.log('Fetching skill files from GitHub...');
  const contents = {};
  for (const file of FILES) {
    contents[file] = await fetchFile(file);
    console.log(`  ✓ ${file} (${contents[file].length} chars)`);
  }

  const outPath = 'src/lib/skill-content.ts';
  mkdirSync(dirname(outPath), { recursive: true });

  const banner = `// AUTO-GENERATED by scripts/fetch-skill.mjs — do not edit by hand.\n// Source: github.com/${REPO_OWNER}/${REPO_NAME}@${BRANCH}\n// Last fetched: ${new Date().toISOString()}\n\n`;

  const exports = FILES.map((file) => {
    const varName = file
      .replace(/^references\//, '')
      .replace(/[.-]/g, '_')
      .replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
      .replace(/^_+/, '')
      .replace(/_+/g, '_');
    return `export const ${varName} = \`${escapeForTemplate(contents[file])}\`;`;
  }).join('\n\n');

  writeFileSync(outPath, banner + exports + '\n');
  console.log(`Wrote ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
